// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZZhjrosMl1rQGKc8cOtCLJRGxZR3VwFE',
    appId: '1:616144928236:web:a7b0edc2dc609a354894c9',
    messagingSenderId: '616144928236',
    projectId: 'warteliste-pro',
    authDomain: 'warteliste-pro.firebaseapp.com',
    storageBucket: 'warteliste-pro.firebasestorage.app',
    measurementId: 'G-7FMGWH7LXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTwl65XaPI4GslqiIxlhFtEQ6PQADLSUs',
    appId: '1:616144928236:android:4075d54d05ecf4874894c9',
    messagingSenderId: '616144928236',
    projectId: 'warteliste-pro',
    storageBucket: 'warteliste-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdsggI7VS4rjuwNGZrdOFBW5yfBh8TkUo',
    appId: '1:616144928236:ios:943f3e07e8bae46a4894c9',
    messagingSenderId: '616144928236',
    projectId: 'warteliste-pro',
    storageBucket: 'warteliste-pro.firebasestorage.app',
    iosBundleId: 'com.hasielektronic.wartelistePro',
  );
}
