name = "warteliste-pro-r2"
main = "src/index.js"
compatibility_date = "2024-01-01"
account_id = "ac6ab4ce1149a3591d014841856490af"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "warteliste-pro-docs"
